import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload migrate:create` — every migration file gets
    // the same (payload, req) signature whether or not a given one needs
    // them, and hand-editing generated migrations defeats their purpose as
    // exact, reproducible output.
    "src/payload/migrations/**",
  ]),
]);

export default eslintConfig;
